runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images

- url: /script
  static_dir: script

- url: /css
  static_dir: css

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
